# Generated by Django 5.1.6 on 2025-03-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rawtext', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField()),
                ('actionables', models.TextField()),
            ],
        ),
    ]
